### ISSUE TITLE
CSV export breaks with "#" in data

### ISSUE THREAD

**Issue by mbrn** [mbrn/filefy#10]
https://github.com/mbrn/material-table/issues/286

**Comment by rbeers** [comment]
I think I found the problem in BaseBuilder.exportFile encodeURI function.

Before encodeURL:
```sh
exportFile => content data:text/csv;charset=utf-8,﻿"Adı","Soyadı","Doğum Yılı","Doğum Yeri"
"Mehmet","Baran",1987,63
"Rob","Beers #",1977,63
"Test","User",1977,63
```

after encodeURI
```sh
exportFile => encodedUri data:text/csv;charset=utf-8,%EF%BB%BF%22Ad%C4%B1%22,%22Soyad%C4%B1%22,%22Do%C4%9Fum%20Y%C4%B1l%C4%B1%22,%22Do%C4%9Fum%20Yeri%22%0D%0A%22Mehmet%22,%22Baran%22,1987,63%0D%0A%22Rob%22,%22Beers%20#%22,1977,63%0D%0A%22Test%22,%22User%22,1977,63
```

When you click on the above URI, it breaks and doesn't show anything after the "#" sign.

Reading the docs at https://www.w3schools.com/jsref/jsref_encodeuri.asp , it states the following:

> This function encodes special characters, except: , / ? : @ & = + $ # (Use encodeURIComponent() to encode these characters).


Perhaps using encodeURIComponent will resolve this??

**Comment by rbeers** [comment]
I gave that a try and this fixed the problem:

BaseBuilder.exportFile:
```js
...
data = encodeURIComponent(data);
var content = "data:text/" + dataType + ";charset=utf-8," + charBom + data;
var link = document.createElement("a");
link.setAttribute("href", content);
...
```

**Comment by mbrn** [comment]
Thanks @rbeers ,

Why you don't contribute to filefy with this solution? Or i will do it later.

**Comment by rbeers** [comment]
I created a branch that fixes the issue and would like to submit a pull request but I get a permission denied when trying to push the branch.

**Comment by mbrn** [comment]
You should fork project and then open a pull request to merge to your own repo.

**Comment by mbrn** [comment]
@rbeers ,

I will publish material-table with filefy@0.1.8 for next release
